const ErrorCode = Object.freeze({
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_NOT_ACTIVATED: "ACCOUNT_NOT_ACTIVATED",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    DB_UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
    DB_RECORD_NOT_FOUND: "DB_RECORD_NOT_FOUND",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
    PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
    PLAN_INACTIVE: "PLAN_INACTIVE",
    PLAN_ALREADY_ACTIVE: "PLAN_ALREADY_ACTIVE",
    PLAN_ALREADY_INACTIVE: "PLAN_ALREADY_INACTIVE",
    STUDENT_ALREADY_SUSPENDED: "STUDENT_ALREADY_SUSPENDED",
    STUDENT_ALREADY_INACTIVE: "STUDENT_ALREADY_INACTIVE",
    STUDENT_ALREADY_ACTIVE: "STUDENT_ALREADY_ACTIVE",
    TEACHER_NOT_FOUND: "TEACHER_NOT_FOUND",
    TEACHER_ALREADY_ACTIVE: "TEACHER_ALREADY_ACTIVE",
    TEACHER_ALREADY_INACTIVE: "TEACHER_ALREADY_INACTIVE",
});

/** @deprecated Usar ErrorCode */
const ERROR_CODES = ErrorCode;

export { ErrorCode, ERROR_CODES };
