const ErrorCode = Object.freeze({
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_NOT_ACTIVATED: "ACCOUNT_NOT_ACTIVATED",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    DB_UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
    DB_RECORD_NOT_FOUND: "DB_RECORD_NOT_FOUND",
});

/** @deprecated Usar ErrorCode */
const ERROR_CODES = ErrorCode;

export { ErrorCode, ERROR_CODES };
